//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _priv_NBSErrorItem : NSObject
{
    int _errCount;
    int _httpMethodNumber;
    NSString *_URI;
    NSString *_urlParams;
    NSString *_params;
    long long _statusCode;
    NSString *_remoteIP;
    NSString *_cdnVendorName;
    long long _httpLibClass;
    long long _appPhase;
}

@property long long appPhase; // @synthesize appPhase=_appPhase;
@property long long httpLibClass; // @synthesize httpLibClass=_httpLibClass;
@property(retain) NSString *cdnVendorName; // @synthesize cdnVendorName=_cdnVendorName;
@property(retain) NSString *remoteIP; // @synthesize remoteIP=_remoteIP;
@property int httpMethodNumber; // @synthesize httpMethodNumber=_httpMethodNumber;
@property int errCount; // @synthesize errCount=_errCount;
@property long long statusCode; // @synthesize statusCode=_statusCode;
@property(retain) NSString *params; // @synthesize params=_params;
@property(retain) NSString *urlParams; // @synthesize urlParams=_urlParams;
@property(retain) NSString *URI; // @synthesize URI=_URI;
- (void).cxx_destruct;
- (id)init;

@end

