//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NBSEventTreeMetric, NBSEventTreeNode, NSTimer;
@protocol OS_dispatch_queue;

@interface NBSEventTree : NSObject
{
    NSObject<OS_dispatch_queue> *queue;
    NSTimer *timer;
    _Bool _abnormal;
    NBSEventTreeNode *_root;
    NBSEventTreeMetric *_metric;
    unsigned long long _lifeRef;
}

@property(nonatomic) _Bool abnormal; // @synthesize abnormal=_abnormal;
@property unsigned long long lifeRef; // @synthesize lifeRef=_lifeRef;
@property(retain, nonatomic) NBSEventTreeMetric *metric; // @synthesize metric=_metric;
@property(retain, nonatomic) NBSEventTreeNode *root; // @synthesize root=_root;
- (void).cxx_destruct;
- (id)cutTree:(id)arg1;
- (void)dealloc;
- (void)fireTimer;
- (void)update;
- (void)fixTree:(id)arg1;
- (void)insertNode:(id)arg1 parent:(id)arg2;
- (id)initWithRootNode:(id)arg1 key:(id)arg2 launchType:(int)arg3;

@end

