//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSString;

@interface NBSEventSegment : NSObject
{
    int _entryCPU;
    int _exitCPU;
    int _eventSegmentType;
    int _callType;
    double _invokeTime;
    double _entryTime;
    long long _entryMemory;
    double _exitTime;
    long long _exitMemory;
    NSString *_eventSegmentName;
    NSString *_threadName;
    unsigned long long _threadId;
    NSArray *_threadInfo;
    NSDictionary *_networkParams;
    unsigned long long _callFromAddr;
    unsigned long long _entryAddr;
}

@property unsigned long long entryAddr; // @synthesize entryAddr=_entryAddr;
@property unsigned long long callFromAddr; // @synthesize callFromAddr=_callFromAddr;
@property(retain) NSDictionary *networkParams; // @synthesize networkParams=_networkParams;
@property(retain) NSArray *threadInfo; // @synthesize threadInfo=_threadInfo;
@property unsigned long long threadId; // @synthesize threadId=_threadId;
@property(retain) NSString *threadName; // @synthesize threadName=_threadName;
@property int callType; // @synthesize callType=_callType;
@property int eventSegmentType; // @synthesize eventSegmentType=_eventSegmentType;
@property(copy) NSString *eventSegmentName; // @synthesize eventSegmentName=_eventSegmentName;
@property long long exitMemory; // @synthesize exitMemory=_exitMemory;
@property int exitCPU; // @synthesize exitCPU=_exitCPU;
@property double exitTime; // @synthesize exitTime=_exitTime;
@property long long entryMemory; // @synthesize entryMemory=_entryMemory;
@property int entryCPU; // @synthesize entryCPU=_entryCPU;
@property double entryTime; // @synthesize entryTime=_entryTime;
@property double invokeTime; // @synthesize invokeTime=_invokeTime;
- (void).cxx_destruct;
- (id)init;

@end

