//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NBSEventSegment, NSMutableArray, NSString;

@interface NBSEventTreeNode : NSObject
{
    _Bool _isFinish;
    NBSEventSegment *_eventSegment;
    NBSEventTreeNode *_parentNode;
    NSMutableArray *_children;
    NSString *_treeKey;
}

@property _Bool isFinish; // @synthesize isFinish=_isFinish;
@property(retain) NSString *treeKey; // @synthesize treeKey=_treeKey;
@property(retain) NSMutableArray *children; // @synthesize children=_children;
@property(retain) NBSEventTreeNode *parentNode; // @synthesize parentNode=_parentNode;
@property(retain) NBSEventSegment *eventSegment; // @synthesize eventSegment=_eventSegment;
- (void).cxx_destruct;
- (id)init;

@end

