//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface NBSLensAppStartsMetrics : NSObject
{
    _Bool _isAppStartsValid;
    long long _count;
    double _sdkStartTimePoint;
    double _appDidFinishLaunchTimePoint;
    double _appDidEnterForegroundTimePoint;
    double _appDidEnterBackGroundTimePoint;
    double _appDidBecomeActiveTimePoint;
    double _appFirstViewDidLoadTimePoint;
    double _appLastVcViewWillAppearTimePoint;
    double _appViewDidAppearTimePoint;
    long long _appPhase;
}

+ (id)sharedInstance;
@property long long appPhase; // @synthesize appPhase=_appPhase;
@property double appViewDidAppearTimePoint; // @synthesize appViewDidAppearTimePoint=_appViewDidAppearTimePoint;
@property double appLastVcViewWillAppearTimePoint; // @synthesize appLastVcViewWillAppearTimePoint=_appLastVcViewWillAppearTimePoint;
@property double appFirstViewDidLoadTimePoint; // @synthesize appFirstViewDidLoadTimePoint=_appFirstViewDidLoadTimePoint;
@property double appDidBecomeActiveTimePoint; // @synthesize appDidBecomeActiveTimePoint=_appDidBecomeActiveTimePoint;
@property double appDidEnterBackGroundTimePoint; // @synthesize appDidEnterBackGroundTimePoint=_appDidEnterBackGroundTimePoint;
@property double appDidEnterForegroundTimePoint; // @synthesize appDidEnterForegroundTimePoint=_appDidEnterForegroundTimePoint;
@property double appDidFinishLaunchTimePoint; // @synthesize appDidFinishLaunchTimePoint=_appDidFinishLaunchTimePoint;
@property double sdkStartTimePoint; // @synthesize sdkStartTimePoint=_sdkStartTimePoint;
@property long long count; // @synthesize count=_count;
@property _Bool isAppStartsValid; // @synthesize isAppStartsValid=_isAppStartsValid;
- (id)init;

@end

