//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NBS_PBS_GCDAsyncSocketDelegate-Protocol.h"

@class NBS_PBS_GCDAsyncSocket, NSData, NSDictionary, NSString, NSThread;

@interface NBSLens_PBS_Request : NSObject <NBS_PBS_GCDAsyncSocketDelegate>
{
    NBS_PBS_GCDAsyncSocket *asyncSocket;
    _Bool _private_condition;
    unsigned short _port;
    unsigned short _currMethod;
    CDUnknownBlockType _callBack;
    unsigned long long _cpType;
    unsigned long long _enType;
    NSString *_host;
    NSDictionary *_header;
    NSData *_sendData;
    NSThread *_com_private_theWaitingThread;
}

@property(retain, nonatomic) NSThread *com_private_theWaitingThread; // @synthesize com_private_theWaitingThread=_com_private_theWaitingThread;
@property(nonatomic) _Bool private_condition; // @synthesize private_condition=_private_condition;
@property(retain, nonatomic) NSData *sendData; // @synthesize sendData=_sendData;
@property(retain, nonatomic) NSDictionary *header; // @synthesize header=_header;
@property(nonatomic) unsigned short currMethod; // @synthesize currMethod=_currMethod;
@property(nonatomic) unsigned short port; // @synthesize port=_port;
@property(retain, nonatomic) NSString *host; // @synthesize host=_host;
@property(nonatomic) unsigned long long enType; // @synthesize enType=_enType;
@property(nonatomic) unsigned long long cpType; // @synthesize cpType=_cpType;
@property(copy, nonatomic) CDUnknownBlockType callBack; // @synthesize callBack=_callBack;
- (void).cxx_destruct;
- (id)alertTextWithErrorStatus:(unsigned short)arg1;
- (void)performBlockOnMain:(id)arg1;
- (void)socket:(id)arg1 didReadData:(id)arg2 withTag:(long long)arg3;
- (void)socketDidDisconnect:(id)arg1 withError:(id)arg2;
- (void)socket:(id)arg1 didWriteDataWithTag:(long long)arg2;
- (void)socket:(id)arg1 didConnectToHost:(id)arg2 port:(unsigned short)arg3;
- (void)syncExecute:(id)arg1 type:(int)arg2 obj:(id)arg3 callBack:(CDUnknownBlockType)arg4;
- (void)asyncExecute:(id)arg1 type:(int)arg2 obj:(id)arg3 callBack:(CDUnknownBlockType)arg4;
- (void)private_signalCondition:(id)arg1;
- (void)signalCondition;
- (_Bool)waitForConditionWithTimeout:(double)arg1;
- (void)disConnectSocket;
- (void)connectSocket;
- (id)encryptData:(id)arg1;
- (id)send_package:(id)arg1 type:(int)arg2;
- (id)getMsgBodyData:(id)arg1;
- (id)convet_license_key:(struct byte_data_s *)arg1;
- (id)getParamData:(int)arg1;
- (unsigned long long)getCurEncryptType;
- (unsigned long long)getAcceptCompressType;
- (id)initWithHost:(id)arg1 port:(unsigned short)arg2;
- (id)init;
- (id)convertHostToAddress:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

