//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSURLConnectionDataDelegate-Protocol.h"
#import "NSURLConnectionDelegate-Protocol.h"

@class NSString;

@interface NBSURLConnectionDelegate : NSObject <NSURLConnectionDelegate, NSURLConnectionDataDelegate>
{
}

- (void)nbs_connection:(id)arg1 didCancelAuthenticationChallenge:(id)arg2;
- (void)nbs_connection:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2;
- (_Bool)nbs_connection:(id)arg1 canAuthenticateAgainstProtectionSpace:(id)arg2;
- (void)nbs_connection:(id)arg1 willSendRequestForAuthenticationChallenge:(id)arg2;
- (_Bool)nbs_connectionShouldUseCredentialStorage:(id)arg1;
- (void)nbs_connection:(id)arg1 didFailWithError:(id)arg2;
- (id)nbs_connection:(id)arg1 willCacheResponse:(id)arg2;
- (id)nbs_connection:(id)arg1 needNewBodyStream:(id)arg2;
- (void)nbs_connectionDidFinishLoading:(id)arg1;
- (void)nbs_connection:(id)arg1 didSendBodyData:(long long)arg2 totalBytesWritten:(long long)arg3 totalBytesExpectedToWrite:(long long)arg4;
- (void)nbs_connection:(id)arg1 didReceiveData:(id)arg2;
- (void)nbs_connection:(id)arg1 didReceiveResponse:(id)arg2;
- (id)nbs_connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

